In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics

In [2]:
df = pd.read_csv('./dataScraping/allPlayers.csv')
print(df)

               PLAYER  GAME  MIN  REB  AST  TO  STL  BLK  PF  PTS  ...  \
0        aaron-gordon     1   39   13    7   1    1    4   2   16  ...
1        aaron-gordon     2   25    6    2   2    0    1   6    8  ...
2        aaron-gordon     3   31    4    2   1    1    0   1   18  ...
3        aaron-gordon     4   30    5    2   1    1    0   2   12  ...
4        aaron-gordon     5   32    1    1   0    0    2   3    9  ...
...               ...   ...  ...  ...  ...  ..  ...  ...  ..  ...  ...
4709  zion-williamson     6   32    1    3   3    1    0   2   30  ...
4710  zion-williamson     7   35    6    5   1    0    1   1   30  ...
4711  zion-williamson     8   30    5    7   4    1    0   2   19  ...
4712  zion-williamson     9   19    6    1   1    1    1   3   12  ...
4713  zion-williamson    10   29    4    6   2    1    1   3   27  ...

      OFFENSE: Pts/Poss  OFFENSE: eFG%  OFFENSE: TOV%  OFFENSE: ORB%  \
0                 120.5          0.578          0.123          0.239
1                 120.9          0.576          0.125          0.251
2                 120.3          0.546          0.118          0.277
3                 119.8          0.545          0.135          0.328
4                 121.7          0.582          0.134          0.283
...                 ...            ...            ...            ...
4709              118.7          0.565          0.125          0.250
4710              118.9          0.562          0.130          0.292
4711              118.7          0.560          0.146          0.303
4712              122.1          0.577          0.130          0.280
4713              115.9          0.569          0.153          0.260

      OFFENSE: FT Rate  DEFENSE: Pts/Poss  DEFENSE: eFG%  DEFENSE: TOV%  \
0                 21.2              112.1          0.525          0.158
1                 23.4              117.5          0.542          0.114
2                 25.7              114.0          0.536          0.145
3                 21.2              113.0          0.543          0.134
4                 18.0              120.7          0.567          0.137
...                ...                ...            ...            ...
4709              20.0              118.7          0.564          0.140
4710              18.0              114.7          0.536          0.125
4711              19.9              118.0          0.548          0.126
4712              21.5              113.7          0.532          0.139
4713              22.0              109.1          0.515          0.145

      DEFENSE: ORB%  DEFENSE: FT Rate
0             0.307              21.4
1             0.263              19.4
2             0.291              22.1
3             0.250              17.7
4             0.297              24.3
...             ...               ...
4709          0.293              20.0
4710          0.267              20.5
4711          0.269              22.1
4712          0.281              19.9
4713          0.263              19.4

[4714 rows x 23 columns]

In [3]:
# Fix string issue
def fix_string_issue (col):
  key = []
  key = df[col].unique()

  for i in range(0, len(df[col].unique())):
    df.loc[df[col] == df[col].unique()[i], col] = i

  return key

pname_key = fix_string_issue('PLAYER')

In [4]:
# Extract features (X) from the last 10 rows (excluding the first)
x = df.drop(columns=['GAME', 'MIN', 'REB', 'AST', 'TO', 'STL', 'BLK', 'PF', 'PTS'])  # All columns except the target column pts

# Extract the target variable (y) for the most recent game
y = df[['MIN', 'REB', 'AST', 'TO', 'STL', 'BLK', 'PF', 'PTS']] # Pts column

In [5]:
x

,PLAYER,W,L,Diff,OFFENSE: Pts/Poss,OFFENSE: eFG%,OFFENSE: TOV%,OFFENSE: ORB%,OFFENSE: FT Rate,DEFENSE: Pts/Poss,DEFENSE: eFG%,DEFENSE: TOV%,DEFENSE: ORB%,DEFENSE: FT Rate
0,0,34.0,15.0,8.4,120.5,0.578,0.123,0.239,21.2,112.1,0.525,0.158,0.307,21.4
1,0,32.0,16.0,3.4,120.9,0.576,0.125,0.251,23.4,117.5,0.542,0.114,0.263,19.4
2,0,30.0,17.0,6.3,120.3,0.546,0.118,0.277,25.7,114.0,0.536,0.145,0.291,22.1
3,0,32.0,17.0,6.8,119.8,0.545,0.135,0.328,21.2,113.0,0.543,0.134,0.250,17.7
4,0,27.0,23.0,1.1,121.7,0.582,0.134,0.283,18.0,120.7,0.567,0.137,0.297,24.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4709,504,26.0,22.0,-0.0,118.7,0.565,0.125,0.250,20.0,118.7,0.564,0.140,0.293,20.0
4710,504,33.0,16.0,4.1,118.9,0.562,0.130,0.292,18.0,114.7,0.536,0.125,0.267,20.5
4711,504,21.0,24.0,0.7,118.7,0.560,0.146,0.303,19.9,118.0,0.548,0.126,0.269,22.1
4712,504,32.0,15.0,8.5,122.1,0.577,0.130,0.280,21.5,113.7,0.532,0.139,0.281,19.9
4713,504,34.0,15.0,6.9,115.9,0.569,0.153,0.260,22.0,109.1,0.515,0.145,0.263,19.4

In [6]:
y

      MIN  REB  AST  TO  STL  BLK  PF  PTS
0      39   13    7   1    1    4   2   16
1      25    6    2   2    0    1   6    8
2      31    4    2   1    1    0   1   18
3      30    5    2   1    1    0   2   12
4      32    1    1   0    0    2   3    9
...   ...  ...  ...  ..  ...  ...  ..  ...
4709   32    1    3   3    1    0   2   30
4710   35    6    5   1    0    1   1   30
4711   30    5    7   4    1    0   2   19
4712   19    6    1   1    1    1   3   12
4713   29    4    6   2    1    1   3   27

[4714 rows x 8 columns]

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)
print(X_test)

     PLAYER     W     L  Diff  OFFENSE: Pts/Poss  OFFENSE: eFG%  \
1210    128  26.0  23.0  -1.8              113.8          0.536
2029    218  24.0  26.0  -3.2              116.3          0.545
3539    380  23.0  25.0   2.7              115.0          0.536
3724    400  32.0  15.0   8.5              122.1          0.577
2256    243   9.0  39.0  -9.8              111.9          0.544
...     ...   ...   ...   ...                ...            ...
73        8  28.0  21.0   3.6              119.7          0.570
4563    489  21.0  27.0  -1.9              118.6          0.541
2521    271  18.0  31.0  -5.7              108.8          0.520
43        5  28.0  19.0   0.1              117.6          0.565
2706    290  10.0  37.0 -11.9              110.6          0.529

      OFFENSE: TOV%  OFFENSE: ORB%  OFFENSE: FT Rate  DEFENSE: Pts/Poss  \
1210          0.136          0.255              22.9              115.5
2029          0.157          0.321              20.8              119.5
3539          0.126          0.264              20.7              112.3
3724          0.130          0.280              21.5              113.7
2256          0.133          0.222              17.9              121.8
...             ...            ...               ...                ...
73            0.149          0.285              24.4              116.1
4563          0.133          0.306              21.7              120.4
2521          0.148          0.263              18.2              114.5
43            0.134          0.264              17.9              117.5
2706          0.139          0.259              17.0              122.5

      DEFENSE: eFG%  DEFENSE: TOV%  DEFENSE: ORB%  DEFENSE: FT Rate
1210          0.559          0.141          0.259              18.3
2029          0.561          0.122          0.273              18.7
3539          0.530          0.137          0.263              22.6
3724          0.532          0.139          0.281              19.9
2256          0.566          0.136          0.321              20.1
...             ...            ...            ...               ...
73            0.544          0.129          0.278              19.0
4563          0.580          0.142          0.282              19.9
2521          0.547          0.153          0.277              21.7
43            0.566          0.138          0.249              21.6
2706          0.586          0.138          0.275              21.3

[943 rows x 14 columns]

In [8]:
from sklearn.ensemble import RandomForestClassifier

In [9]:
model = RandomForestClassifier(n_estimators= 1000, random_state = 42)

In [10]:
model.fit(X_train, Y_train)
prediction_test = model.predict(X_test)
prediction_test

array([[32,  5,  5, ...,  1,  2,  8],
       [ 8,  0,  0, ...,  0,  2,  5],
       [27,  7,  1, ...,  3,  1, 14],
       ...,
       [23,  3,  0, ...,  1,  1,  0],
       [18,  0,  0, ...,  0,  2,  5],
       [29,  4,  3, ...,  0,  3, 25]], dtype=int64)

In [11]:
# Check accuracy
acc = 0
acceptable_range = 3

Y_test_np = Y_test.values

for i in range(0, len(prediction_test)):
    for j in range(0, len(prediction_test[0])):
        acc += 0 if abs(Y_test_np[i, j]-prediction_test[i, j]) > acceptable_range else 1
acc /= len(prediction_test)*len(prediction_test[0])
print("Accuracy = ", acc)

Accuracy =  0.7058589607635207

In [12]:
# Saving/loading model
import joblib

def model_save ():
    joblib.dump(model, 'player-stats.joblib')

def model_load():
    model = joblib.load('player-stats.joblib')

In [13]:
# Save model (14.2 GB holy fuck)
model_save()

In [14]:
# Check which features contribute the most
feature_list = list(x.columns)
feature_imp = pd.Series(model.feature_importances_, index = feature_list).sort_values(ascending = False)
feature_imp

PLAYER               0.958869
OFFENSE: TOV%        0.003475
DEFENSE: ORB%        0.003428
DEFENSE: TOV%        0.003352
OFFENSE: ORB%        0.003314
OFFENSE: FT Rate     0.003292
OFFENSE: eFG%        0.003186
OFFENSE: Pts/Poss    0.003182
DEFENSE: FT Rate     0.003166
DEFENSE: Pts/Poss    0.003105
Diff                 0.003011
DEFENSE: eFG%        0.002964
W                    0.002840
L                    0.002817
dtype: float64